<Project Sdk="MSTest.Sdk/4.1.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LatencyPilot.Core/LatencyPilot.Core.csproj" />
    <ProjectReference Include="../../src/LatencyPilot.Benchmarking/LatencyPilot.Benchmarking.csproj" />
    <ProjectReference Include="../../src/LatencyPilot.Protocol/LatencyPilot.Protocol.csproj" />
    <ProjectReference Include="../../src/LatencyPilot.Platform.Windows/LatencyPilot.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
