<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ManagedNativeWifi" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="Vortice.DXGI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../LatencyPilot.Core/LatencyPilot.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LatencyPilot.CriticalTests" />
  </ItemGroup>
</Project>
